cache:
  directories:
  - $TRAVIS_BUILD_DIR/build/native/x86_64-unknown-linux-gnu
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y yasm
language: java
install: ant clean stage 
script: ant run-tests-native
